### ISSUE TITLE
ERROR (SyncWorker_0) [custom_components.sensor.HeWeather] Json Status Not Good!

### ISSUE THREAD

**Issue by Dbarl** [charleyzhu/HomeAssistant_Components#1]
When I tried to add the Heweather to hassio, log feedback gave me a mistake:

> ERROR (SyncWorker_0) [custom_components.sensor.HeWeather] Json Status Not Good!

**Comment by charleyzhu** [comment]
this error is HeWeather return Status Error

**Comment by Dbarl** [comment]
Thanks.
