### ISSUE TITLE
DLNA运行中的错误提示，劳烦帮忙看看，谢谢

### ISSUE THREAD

**Issue by kukudemajia** [charleyzhu/HomeAssistant_Components#3]
出现以下错误，请问怎么解决呢？
2017-08-08 18:19:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.5fbeacdc86e246f7942d7c962294d468 fails
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
yield from self.hass.async_add_job(self.update)
File "/usr/lib/python3.5/asyncio/futures.py", line 380, in iter
yield self # This tells Task to wait for completion.
File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
future.result()
File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
raise self._exception
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/root/.homeassistant/custom_components/media_player/dlna.py", line 71, in update
resp = self._device.GetTransportInfo()
File "/root/.homeassistant/custom_components/media_player/dlna.py", line 304, in GetTransportInfo
["CurrentTransportState", "CurrentTransportStatus", "CurrentSpeed"])
File "/root/.homeassistant/custom_components/media_player/dlna.py", line 423, in sendRequest
respXml = etree.fromstring(respText)
File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1345, in XML
return parser.close()
File "", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

识别出三个设备，其中有小米电视机2，还有安桥功放机
我的小米电视机可以TTS播放没问题
我现在是想直接连接我的安桥功放机输出声音，但是不成功，会自动切换到DLNA状态
但是没有声音输出
系统运行后台日志总是出现类似上面的出错提示哦

**Comment by charleyzhu** [comment]
兼容性问题，我只能说适配了一部分设备，写代码的时候家里只有小米和叮咚音响

**Comment by kukudemajia** [comment]
能用其实已经不错了，谢谢了
我附上我的安桥功放机ht-r758的
http://192.168.0.192:8888/upnp_descriptor_0
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>HT-R758</friendlyName>
<manufacturer>ONKYO</manufacturer>
<manufacturerURL>http://www.onkyo.com</manufacturerURL>
<modelDescription>AV Receiver</modelDescription>
<modelName>HT-R758</modelName>
<modelNumber>HT-R758</modelNumber>
<modelURL>http://www.onkyo.com</modelURL>
<UDN>uuid:021c7600-6c76-0074-721e-00686c740470</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<controlURL>/upnp_control_0</controlURL>
<eventSubURL>/upnp_event_0</eventSubURL>
<SCPDURL>/scpd/RenderingControl_1</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/upnp_control_1</controlURL>
<eventSubURL>/upnp_event_1</eventSubURL>
<SCPDURL>/scpd/ConnectionManager_1</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<controlURL>/upnp_control_2</controlURL>
<eventSubURL>/upnp_event_2</eventSubURL>
<SCPDURL>/scpd/AVTransport_1</SCPDURL>
</service>
</serviceList>
<presentationURL>http://192.168.0.192/</presentationURL>
<pnpx:X_hardwareId xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11">VEN_1666&DEV_1200&REV_01 VEN_0033&DEV_000C&REV_01</pnpx:X_hardwareId>
<dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
<df:X_deviceCategory xmlns:df="http://schemas.microsoft.com/windows/2008/09/devicefoundation">Multimedia.DMR</df:X_deviceCategory>
<pnpx:X_compatibleId xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11">MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
<iconList>
<icon>
<mimetype>image/jpeg</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_120.jpg</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_048.jpg</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>32</width>
<height>32</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_032.jpg</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_120.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_048.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>32</width>
<height>32</height>
<depth>24</depth>
<url>http://192.168.0.192/icon/AVR_032.png</url>
</icon>
</iconList>
<pnpx:X_deviceCategory xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11">MediaDevices</pnpx:X_deviceCategory>
<microsoft:magicPacketWakeSupported xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0">0</microsoft:magicPacketWakeSupported>
<microsoft:X_magicPacketSendSupported xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0">1</microsoft:X_magicPacketSendSupported>
</device>
</root>

**Comment by kukudemajia** [comment]
目前这个功放机的DLNA无法兼容
