### ISSUE TITLE
请问大神您这里的dingdong.py是干什么用的？怎么使用？

### ISSUE THREAD

**Issue by yingzaigt** [charleyzhu/HomeAssistant_Components#5]
请问大神您这里的dingdong.py是干什么用的？怎么使用？能详细说一下吗？目前手里有叮咚智能音箱，想充分利用一下。大概看了一下代码，好像可以用叮咚智能音箱语音控制homeassistant，但是具体怎么用没看明白。请大神不吝赐教。谢谢！

**Comment by charleyzhu** [comment]
本来在写叮咚的，这是预留的api，现在工作忙成狗模式，叮咚暂时搁置了
