### ISSUE TITLE
您好 DLNA.py 这个如何使用呢？

### ISSUE THREAD

**Issue by HuaianWu** [charleyzhu/HomeAssistant_Components#8]
能请假一下 DLNA 组件如何使用吗~谢谢！

**Comment by charleyzhu** [comment]
不用考虑如何使用，放到目录中就会出现mediaplay

**Comment by HuaianWu** [comment]
您好，我按照 readme 说的放到配置文件所在目录的 custom_component 目录下 可是运行时说找不到这个组件是为什么呢？我也尝试放到系统文件那个目录下，可是提示我没有权限，也没法赋予权限，我是不是应该以 root 用户登陆呢？密码是多少呢？刚研究 ha 希望能赐教😊

**Comment by charleyzhu** [comment]
请仔细查看，在多个目录中有dlna.py
