### ISSUE TITLE
ha 0.73版本出现emulated_hue_charley报错的问题，该如何破？

### ISSUE THREAD

**Issue by plutosherry** [charleyzhu/HomeAssistant_Components#9]
ha 0.73版本出现emulated_hue_charley报错的问题，该如何破？
貌似是ha升级后对安全方面做了一些设置而导致的。

`Log Details (ERROR)
Sat Jul 14 2018 11:59:30 GMT+0800 (中国标准时间)

Error during setup of component emulated_hue_charley
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/emulated_hue_charley/__init__.py", line 107, in setup
    is_ban_enabled=False
TypeError: __init__() missing 2 required positional arguments: 'ssl_peer_certificate' and 'trusted_proxies'`

`You are using a custom component for emulated_hue_charley which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

**Comment by charleyzhu** [comment]
你用了https？

**Comment by plutosherry** [comment]
没有用https
后来修改了如下文件后正常了。。。。
查找__init__.py中的is_ban_enabled=False处，在其后增加两行代码：
trusted_proxies=[],
ssl_peer_certificate=None
貌似0.73后HA默认是要检查ssl的？

**Comment by charleyzhu** [comment]
ssl_peer_certificate是指定证书的，这个模拟器是修改官方的，你设置前需要查询相关文档
